// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8TH9BewtCJZpf3akmNWLhi64iJ0VIRnM',
    appId: '1:674664218869:web:cdf1d7695af858b79445bc',
    messagingSenderId: '674664218869',
    projectId: 'journal-app-dfb1d',
    authDomain: 'journal-app-dfb1d.firebaseapp.com',
    storageBucket: 'journal-app-dfb1d.firebasestorage.app',
    measurementId: 'G-N0RBLKDD7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByPEzAhbFC8WBgjpIhl3nxxIxTQSZ1-IE',
    appId: '1:674664218869:android:d6dc9f359f55422a9445bc',
    messagingSenderId: '674664218869',
    projectId: 'journal-app-dfb1d',
    storageBucket: 'journal-app-dfb1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsmHJyGkRZGcnquNzGwCw3bAXFTDtPiGQ',
    appId: '1:674664218869:ios:8858434aec6541719445bc',
    messagingSenderId: '674664218869',
    projectId: 'journal-app-dfb1d',
    storageBucket: 'journal-app-dfb1d.firebasestorage.app',
    iosBundleId: 'com.example.journalapp',
  );
}
